### ISSUE TITLE
Make the code blacklist to another file?

### ISSUE THREAD

**Issue by CosmicWebServices** [LilCoders/Editor-Player#3]
I mean there are ups and downs someone can simply drop that file when they get to it but also it may help the developers

**Comment by JordanB-1337** [comment]
"someone can simply drop that file when they get to it " What do you mean? Even if they remove it for them, other people will still be protected.

**Comment by CosmicWebServices** [comment]
There is stuff u can do to disable scripts on sites. If it is on main.js they cannot use the site if they drop it

**Comment by JordanB-1337** [comment]
They can disable it for themselves all they like. The problem is disabling it for everyone.


(Also, you could still remove it even from the same file using inspect element)

**Comment by CosmicWebServices** [comment]
Oh true so make it separate files I think is a good idea (making a pr right now)

**Comment by JordanB-1337** [comment]
Yeah I think we should move it too.

**Comment by CosmicWebServices** [comment]
OK I will do it

**Comment by CosmicWebServices** [comment]
Done
